version: 2

before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
  - -s -w
  - -X github.com/timebertt/kubectl-revisions/pkg/cmd/version.version=v{{ .Version }}

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

archives:
- formats: [tar.gz]
  name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  # use zip for windows archives
  format_overrides:
  - goos: windows
    formats: [zip]

changelog:
  use: github

snapshot:
  version_template: "{{ incminor .Version }}-dev-{{ .ShortCommit }}"
